### ISSUE TITLE
获取的颜色值和antd色彩生成的值，对应不是

### ISSUE THREAD

**Issue by jiangqidu** [luffyZh/mini-dynamic-antd-theme#12]
![2021-09-06_113948](https://user-images.githubusercontent.com/55723376/132157699-ea8888a5-3020-4c95-9ee3-74752c90a5ad.jpg)
![QQ截图20210906114102](https://user-images.githubusercontent.com/55723376/132157714-4c46be10-7bc2-4302-95e9-2c4b9188523c.png)
目前想要获取color-5的颜色值作为经过色，想要获取color-7的值作为链接色，但是不知道怎么用这个插件实现

**Comment by luffyZh** [comment]
我这边还真没考虑过这一点，就是除了 primary 之外，其他的都是我去计算的，你可以自己拿去改一下


| |
周公子
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年09月6日 ***@***.***> 写道：



目前想要获取color-5的颜色值作为经过色，想要获取color-7的值作为链接色，但是不知道怎么用这个插件实现

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
