### ISSUE TITLE
默认会设置一个值为#1890ff的mini-dynamic-antd-theme-color

### ISSUE THREAD

**Issue by jiangqidu** [luffyZh/mini-dynamic-antd-theme#13]
如果用户自己定义一套主题色，那么就会出现找不到值的情况，比如
![848904](https://user-images.githubusercontent.com/55723376/132182808-33a6c5a9-7073-40ad-a0c6-969933dab57b.png)
但是我的颜色取值不是antd的默认值，就会出现一些问题
![QQ截图20210906160857](https://user-images.githubusercontent.com/55723376/132182988-3cc18b65-19e5-4590-86db-41fb684f2059.png)

**Comment by luffyZh** [comment]
自定义颜色，没关系吧，你只要修改的时候传入到组件里就行啦


| |
周公子
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年09月6日 ***@***.***> 写道：

如果用户自己定义一套主题色，那么就会出现找不到值的情况，比如

但是我的颜色取值不是antd的默认值，就会出现一些问题


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luffyZh** [comment]
Zhoudeyou945 我微信


| |
周公子
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年09月6日 ***@***.***> 写道：

如果用户自己定义一套主题色，那么就会出现找不到值的情况，比如

但是我的颜色取值不是antd的默认值，就会出现一些问题


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
